packages/layout/src/components/AppFooter.tsx, packages/layout/src/components/AppHeader.tsx, packages/layout/src/components/Copyright.tsx, packages/layout/src/components/__test__/Copyright.snapshot.test.tsx
https://medium.com/front-end-weekly/jest-snapshot-testing-with-dates-and-times-f3badb8f1d87
=> test(layout): fix failing snapshot test

packages/ui/public/accordion-theme.css, packages/ui/public/tab-theme.css, packages/ui/src/components/Accordion/AccordionTitle.tsx, packages/ui/src/components/Accordion/__test__/__snapshots__/Accordion.snapshot.test.tsx.snap, packages/ui/src/components/Accordion/__test__/__snapshots__/AccordionTitle.snapshot.test.tsx.snap, packages/ui/src/components/Accordion/accordion.css, packages/ui/src/components/TabbedPanel/tabs.css
```jsx
import "@dzangolab/react-ui/dist/TabTheme.css";
import "@dzangolab/react-ui/dist/AccordionTheme.css";
```
import above themes in the react-app to get default look
=> Feat(refactor): accordion tab theme

packages/ui/public/accordion-theme.css, packages/ui/src/components/Accordion/Accordion.tsx
1. fix style for edge casew (nested accordions)
2. use more appropriate prop name
=> feat(ui): use more appropriate prop name

packages/ui/src/components/Page/index.tsx, packages/ui/src/components/Page/page.css
https://beta.reactjs.org/learn/conditional-rendering#conditionally-assigning-jsx-to-a-variable
=> feat(ui): add error component

pnpm-lock.yaml, tools/eslint-config-custom/package.json
=> Revert "fix(deps): update dependency eslint-config-next to v13.2.3"

packages/user/src/assets/css/index.css, packages/user/src/assets/css/profileInformation.css, packages/user/src/components/ProfileInformation.tsx, packages/user/src/components/__test__/ProfileInformation.snapshot.test.tsx, packages/user/src/components/__test__/__snapshots__/ProfileInformation.snapshot.test.tsx.snap, packages/user/src/index.ts, packages/user/src/views/Profile.tsx
=> Revert "refactor: remove profile page from user "

packages/ui/src/Buttons/ExportButton/index.tsx, packages/ui/src/utils/UseExporterAsync.ts, packages/ui/src/utils/index.ts, packages/ui/vite.config.ts
also added separate asynchronous version: triggerExportAsync
=> fix(exporter): make default exporter synchronous

CHANGELOG.md, package.json, packages/config/package.json, packages/form/package.json, packages/i18n/package.json, packages/layout/package.json, packages/ui/package.json, packages/user/package.json, pnpm-lock.yaml, tools/eslint-config-custom/package.json, tools/tsconfig/package.json
=> Revert "chore: release v0.18.0"

apps/demo/src/Views/Ui/index.tsx, packages/ui/src/DataTable/Table.tsx, packages/ui/src/DataTable/WrapColumnBody.tsx, packages/ui/src/FileCard/index.tsx, packages/ui/src/FilesTable/index.tsx, packages/user/src/supertokens/index.ts, packages/user/src/views/Signup.tsx
refactor(ui/FilesTable): default props value and Ifile types
=> fix(ui/DataTable): tooltip render issue

packages/user/src/views/Login.tsx, packages/user/src/views/VerifyEmail.tsx
=> feat(login-redirect): redirect to verify page after login

apps/demo/src/Views/User/index.tsx, apps/demo/src/locales/en/users.json, apps/demo/src/locales/fr/users.json, packages/i18n/src/locales/en/users.json, packages/i18n/src/locales/fr/users.json, packages/user/src/components/UsersTable/UsersTable.tsx
=> refactor(usersTable): update users table to use tanstack data table

packages/layout/src/assets/css/layouts/sidebar-header-layout.css
=> Revert "fix(sidebar-menu): improve the condition to hide user-menu in sidebar"

apps/demo/src/constants.ts, packages/layout/src/assets/css/layouts/sidebar-header-layout.css, packages/layout/src/layouts/SidebarHeaderLayout.tsx, packages/user/src/layouts/UserEnabledSidebarHeaderLayout.tsx
=> fix(sidebar-menu): change implementation for hiding submenu

packages/form/src/components/Select.tsx, packages/ui/src/Select/index.tsx
=> refactor(select): add prop for default select in case of single option

packages/ui/src/Select/index.tsx, packages/ui/src/assets/css/select.css
=> refactor(ui/select): allow user to remove selected option only when field is not disabled in multiselect mode

packages/form/src/components/File/SelectedFile/SelectedFile.tsx, packages/ui/src/Tooltip/Tooltip.tsx, packages/user/src/components/Invitation/InvitationsTable.tsx
=> refactor(form): replace the tooltip and input component

packages/ui/src/assets/css/reset.css
See https://dev.polifonic.io/tech:css:start#__font
=> feat: update font stack to use system ui font

packages/user/src/context/UserProvider.tsx, packages/user/src/hooks/useEmailVerification.ts, packages/user/src/supertokens/superTokens.ts, packages/user/src/types/config.ts
BREAKING GHANGE: use separate features.emailVerification config to enable/disable email verification
=> fix(user)!: use independent feature config for email verification

packages/layout/src/assets/css/components/layout/sidebar.css, packages/layout/src/components/Layout/Layout.tsx, packages/layout/src/components/Layout/common/Toggle/ToggleMenuMobile.tsx, packages/layout/src/components/Layout/common/Toggle/ToggleSidebar.tsx, packages/layout/src/components/Layout/index.ts, packages/layout/src/context/LayoutProvider.tsx, packages/layout/src/index.ts
- move layout context to a separate context folder
- fix typo
- hide horizontal scrollbar for sidebar
=> fix(layout): hide horizontal scrollbar in sidebar component

packages/form/src/assets/css/form.css, packages/form/src/assets/css/index.css, packages/form/src/assets/css/vars.css, packages/ui/src/assets/css/form-widgets/field.css
Reverts prefabs-tech/react#1576
=> Revert "fix(form): gap between the form fields"

packages/ui/src/Table/Table.tsx, packages/ui/src/Table/TableHeader.tsx, packages/ui/src/Table/types.ts
=> feat(ui): optional highlighting for active sorting and filtering

packages/layout/src/assets/css/components/layout/header-menu.css, packages/ui/src/Pagination/index.tsx, packages/ui/src/assets/css/dropdown-menu.css, packages/ui/src/assets/css/index.css, packages/ui/src/assets/css/pagination.css, packages/ui/src/assets/css/table.css, packages/ui/src/assets/css/vars.css
=> feat(ui/table): remove header and pagination background
